extends Node
## The game's sound effects: what they are called, where they live, and how to
## play one.
##
## Deliberately not `class_name`-d: the autoload name is Sfx already.
##
## This is the audio half of the contract Sheet is the art half of. Both are
## deliberately dumb about how the thing is made: the sheet is a PNG and the effect
## is a WAV, and the game only ever asks for one by name. A replacement effect is a
## file called the same thing, and no code changes - which is the property that
## matters, because the day the game grows a synthesiser in it is the day the
## effects stop being replaceable.
##
## The effects themselves are generated by tools/make_sfx.gd from the recipes in
## tools/sfx_art.gd, and committed. So there is exactly one description of each
## sound, and the suite can check the committed files against it.
##
## Autoloaded, so the title screen can make noise as well as the game, and so
## nothing has to be threaded through to be able to play a sound.
##
## Effects are played on a small pool of players rather than one per sound. A level
## can drop three parts in the same frame and the player has just thrown pepper at
## four nasties; a pool means those overlap instead of cutting each other off, and
## a pool that ran out drops the new sound rather than stalling the frame waiting
## for a player to free up.

## Where the committed effects are.
const DIR := "res://assets/sfx/"

## How many can sound at once. Six is comfortably more than the game has ever
## needed at one instant, and small enough that the pool is not a thing to think
## about.
const POOL := 6

## The effect a sound plays at, in db. Effects sit well below the level they are
## layered over, so nothing here competes with a jingle when the two overlap.
const VOLUME_DB := -6.0

## Loaded streams by name, so a sound asked for every frame is only loaded once.
static var _cache := {}

var _players: Array[AudioStreamPlayer] = []


func _ready() -> void:
	# Built in _ready rather than as a static list of nodes so the pool is created
	# with the autoload and lives exactly as long as it does. Godot's own audio is
	# up before autoloads, so the players are safe to make here.
	for i in POOL:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_players.append(p)


## Plays an effect by name.
##
## A missing effect is reported and otherwise ignored, matching what Sheet.texture
## does with a missing sheet: the game should still run and say what is wrong. The
## alternative is a null stream reference that takes the level down with it, and a
## bug report that says the game crashed rather than the one that says the sound
## is missing.
func play(name: String, volume_db: float = VOLUME_DB) -> void:
	var stream := stream_for(name)
	if stream == null:
		return
	var p := _take_player()
	if p == null:
		return
	p.stream = stream
	p.volume_db = volume_db
	p.play()


## A player to play on, or null if there is none.
##
## A free one if there is a free one, so overlapping effects layer instead of
## cutting each other off: a chef can drop three parts in a frame, and a second
## stack landing on the same plate should be heard as well as the first. Only when
## every player is busy is one taken, and then the one with least left to play, so
## what gets cut is the effect nearest its end rather than whichever happened to be
## started first. Handing back null rather than blocking is deliberate - a sound is
## not worth stalling a frame for, and a dropped effect is a far smaller problem
## than a stutter.
func _take_player() -> AudioStreamPlayer:
	var quietest: AudioStreamPlayer = null
	var quietest_left := INF
	for p in _players:
		if not p.playing:
			return p
		var left := p.get_playback_position() + p.stream.get_length() \
				- AudioServer.get_time_since_last_mix() - AudioServer.get_output_latency()
		if left < quietest_left:
			quietest_left = left
			quietest = p
	return quietest


## The effect by name, or null if the file is missing.
static func stream_for(name: String) -> AudioStream:
	if _cache.has(name):
		return _cache[name]
	var path := DIR + name + ".wav"
	if not ResourceLoader.exists(path):
		push_error("no effect at %s: run godot --headless --script res://tools/make_sfx.gd, then --import" % path)
		_cache[name] = null
		return null
	var stream := load(path) as AudioStream
	_cache[name] = stream
	return stream

