class_name SfxArt
extends RefCounted
## Sound effect generator, not part of the game.
##
## The same arrangement the character sheets use, for the same reason. The sheets
## are generated by `tools/make_sheets.gd` and committed, so the game has no art
## code in it and a replacement is a PNG with the right name. The effects are
## generated by `tools/make_sfx.gd` and committed for exactly the same reason: the
## game should have no synthesis code in it, and swapping a sound is dropping in a
## WAV called the same thing.
##
## So this file holds the *recipes* and `Sfx` holds the *contract* - the names, the
## directory, and the lookup - and neither the game nor the tests know how a sound
## is made. They only know what it is called.
##
## Everything is synthesised from oscillators and a seeded noise source, with no
## samples and no imports, so the output is reproducible byte for byte. That is
## testable in a way a folder of downloaded audio is not: the suite regenerates
## every effect and compares it against the committed WAV, so an effect that was
## edited by hand and an effect whose recipe was changed are told apart.
##
## The sound is 16 bit mono at 22.05 kHz, which is what a period sound card of the
## kind this is imitating put out, and it is short - an effect that is still being
## heard when the next one fires is two effects.

## Sample rate. Low on purpose, and the same for every effect so nothing needs
## converting: it is what gives the lot their shared, slightly soft character, and
## it keeps the committed files small enough to sit in the repo.
const RATE := 22050

## Every effect, in the order the sheet lists its animations: the ones the chef
## does, then the ones the food does, then the ones the level does.
const SOUNDS := [
	"jump", "land", "step", "step_soft", "spray", "zap", "deny",
	"drop", "stack", "burger", "squash", "ride",
	"bonus", "death", "respawn", "level_clear", "game_over", "win",
]


## Renders one effect by name, as mono samples in -1..1.
##
## The voices are listed rather than generated from a table because each effect is
## a shape, and a shape reads far better written out than parameterised into
## something general enough to also produce shapes nobody wanted.
static func wave(name: String) -> PackedFloat32Array:
	match name:
		"jump": return _jump()
		"land": return _land()
		"step": return _step()
		"step_soft": return _step_soft()
		"spray": return _spray()
		"zap": return _zap()
		"deny": return _deny()
		"drop": return _drop()
		"stack": return _stack()
		"burger": return _burger()
		"squash": return _squash()
		"ride": return _ride()
		"bonus": return _bonus()
		"death": return _death()
		"respawn": return _respawn()
		"level_clear": return _level_clear()
		"game_over": return _game_over()
		"win": return _win()
	push_error("no recipe for sound %s" % name)
	return PackedFloat32Array()


## The effect by name, as a 16 bit mono WAV file.
##
## A real RIFF/WAVE rather than a ResourceSaver .res, so the file is an ordinary
## asset the importer handles like any other and can be opened by anything else.
static func wav(name: String) -> PackedByteArray:
	var s := wave(name)
	var body := PackedByteArray()
	body.resize(s.size() * 2)
	for i in s.size():
		body.encode_s16(i * 2, int(clampf(s[i], -1.0, 1.0) * 32767.0))
	# The header is exactly 44 bytes and every field in it is at a known offset.
	# It is built in its own buffer and the samples appended after it, rather than
	# sizing one buffer up front: sizing it first and appending afterwards silently
	# writes the samples *past* the chunk the header declares, and every file comes
	# out the right shape and completely silent.
	var head := PackedByteArray()
	head.resize(44)
	_blit(head, 0, "RIFF")
	head.encode_u32(4, 36 + body.size())  # everything after this field
	_blit(head, 8, "WAVE")
	_blit(head, 12, "fmt ")
	head.encode_u32(16, 16)  # the size of this chunk
	head.encode_u16(20, 1)  # PCM, not a compressed format
	head.encode_u16(22, 1)  # mono
	head.encode_u32(24, RATE)
	head.encode_u32(28, RATE * 2)  # bytes a second, at 16 bit mono
	head.encode_u16(32, 2)  # one frame is two bytes
	head.encode_u16(34, 16)  # and it is 16 bits wide
	_blit(head, 36, "data")
	head.encode_u32(40, body.size())
	var out := head
	out.append_array(body)
	return out


## Writes a four character code at an offset: the RIFF fields that are words
## rather than numbers.
static func _blit(out: PackedByteArray, at: int, chunk: String) -> void:
	for i in 4:
		out[at + i] = chunk.unicode_at(i)


# --- Recipes -----------------------------------------------------------------
#
# The house rules these follow, so a new effect fits in beside the old ones:
# short, pitched or noise-based rather than sampled, and it always *lands* - the
# last few milliseconds fade rather than stop, because an effect that stops at
# full volume is a click, and a screenful of clicks is worse than no sound.
#
# Pitches are real frequencies in hertz, in the same register throughout, and
# every one of them is a note you could find on a keyboard. A jingle whose
# frequencies are 0.523 rather than 523 is a jingle nobody can hear, which is a
# mistake worth making exactly once.

## The shortest ramp any effect gets, whether or not its recipe asks for one, in
## seconds. A square wave that starts at full amplitude is a discontinuity in the
## waveform, which is exactly what a click is; four milliseconds is far too short to
## hear as a swell and is enough to round the corner off. Applied by the callers as
## a fraction of the effect, so it is a fixed time rather than a fixed proportion -
## the same 4 ms on a 60 ms blip and a 600 ms jingle.
const MIN_ATTACK := 0.004

const C4 := 261.6
const E4 := 329.6
const F4 := 349.2
const G3 := 196.0
const G2 := 98.0
const A3 := 220.0
const C5 := 523.3
const E5 := 659.3
const G4 := 392.0
const G5 := 784.0
const A5 := 880.0
const C6 := 1046.5
const B5 := 987.8
const D6 := 1174.7


## The chef's push-off. An octave up on a light square: he goes up, so it goes up.
## The slide is the whole effect - a stepped octave would be two beeps.
static func _jump() -> PackedFloat32Array:
	return _voice(0.11, C5, C6, 0.3, 0.0, 3.0, 0.0, 0.25)


## Landing. A low thud a fifth down with noise for the contact, because weight is
## mostly the part you hear as impact. Much shorter than the jump: a landing is the
## end of something rather than a moment of its own.
static func _land() -> PackedFloat32Array:
	return _voice(0.07, G3, G2, 0.34, 0.0, 5.0, 0.18, 0.5)


## A step, as an arcade "wocka": one short square note whose pitch sweeps up and
## back down inside the sound. A footfall used to be a filtered noise thud, which a
## run repeated into a flat scuffing buzz; a warble has a shape, so a run reads as
## a row of little munchers instead. It stays a footstep - the pair is still played
## every other cell and still alternates - only the shape of one step changed.
static func _step() -> PackedFloat32Array:
	return _wocka(0.062, 232.0, 520.0, 0.34, 0.5)


## The other foot. The same wocka a little lower and quieter, so alternating the two
## does not read as a two-beat rhythm - the point is that the chef does not sound
## like he is stamping in time.
static func _step_soft() -> PackedFloat32Array:
	return _wocka(0.054, 174.0, 392.0, 0.28, 0.5)


## The seasoning spray. Noise, lowpassed by a filter that closes as it goes, so it
## starts as a hiss and sifts down into a puff. Deliberately unpitched: a note
## would have described something with a pitch, and pepper has none.
static func _spray() -> PackedFloat32Array:
	return _noise(0.19, 0.55, 0.06, 0x5b1a, 0.5, 3.0, 0.0, 0.006)


## A dose that landed on something. A hard square dropping three octaves and cut
## off short, which is the arcade shorthand for a zap. Landing and missing it
## cannot sound alike, because one has a pitch and the other does not.
static func _zap() -> PackedFloat32Array:
	return _voice(0.12, A5, A3, 0.3, 0.0, 3.0, 0.0, 0.5)


## The key pressed with an empty jar. Two low notes, and the repeat is what makes
## it read as a refusal rather than as a note - the same two-note shape as the
## ride, but down where a wrong answer belongs.
static func _deny() -> PackedFloat32Array:
	return _voice(0.16, A3, G3, 0.3, 0.0, 4.0, 0.0, 0.5, 0.0, true)


## A part letting go of its floor. Down a long way, with noise scraped underneath,
## the same shape as the landing but longer and softer - a part arriving is not
## the same event as a chef arriving.
static func _drop() -> PackedFloat32Array:
	return _voice(0.16, G4, 147.0, 0.3, 0.006, 3.5, 0.22, 0.5)


## A part landing on a plate. Brighter, shorter, and *rising*: the stack is getting
## taller and the effect should not fight the drop it is answering by falling too.
static func _stack() -> PackedFloat32Array:
	return _voice(0.06, G5, C6, 0.28, 0.002, 2.0, 0.0, 0.25)


## A finished burger. Three notes of a C major triad. The first three notes of a
## scale is the whole of a jingle, and stretching it further would mean waiting to
## find out whether the level was clear.
static func _burger() -> PackedFloat32Array:
	return _arp([C5, E5, G5], 0.05, 3.0, 3.0)


## A nasty flattened. Noise with the filter closing fast over a body tone, so it is
## a splat and not a hiss. The body is what gives it weight.
static func _squash() -> PackedFloat32Array:
	var out := _noise(0.17, 0.7, 0.03, 0x5c11a, 0.42, 2.6, 0.0, 0.004)
	var body := _voice(0.17, 300.0, 90.0, 0.34, 0.0, 2.6, 0.0, 0.5)
	for i in mini(out.size(), body.size()):
		out[i] += body[i]
	return out


## A nasty picked up. Two notes a fifth down. A gift of a sound, brighter than the
## deny it rhymes with, so the two are not confused in a noisy room.
static func _ride() -> PackedFloat32Array:
	return _arp([G5, C5], 0.045, 2.0, 3.0)


## A bonus collected. The brightest thing in the game and the only jingle on a
## triangle: it is a gift, not a machine.
static func _bonus() -> PackedFloat32Array:
	return _arp([E5, B5], 0.05, 3.0, 3.0, 0.25)


## Being caught. The longest fall in the game and the only one that ends below
## where it started, because it is the one moment the player did not choose. The
## tremble closes up as the note falls, so the fall is unsteady at the top and
## settles at the bottom - the difference between "you lost" and "a noise".
static func _death() -> PackedFloat32Array:
	var n := int(0.44 * float(RATE))
	var out := PackedFloat32Array()
	out.resize(n)
	for i in n:
		var t := float(i) / float(n)
		var f := lerpf(G4, 110.0, t) + sin(t * 44.0) * 0.055 * (1.0 - t)
		out[i] = _square(_phase(float(i) / float(RATE), f), 0.5) \
				* _envelope(t, _attack(0.01, n), 1.5) * 0.34
	return out


## Coming back down under the canopy. Noise alone, and the filter *opens* across
## it - the opposite of the spray, doing the same job in reverse. The player has
## just heard a fall and now hears a rise, and it is held for the first two thirds
## so it sounds like something arriving rather than something fading in.
static func _respawn() -> PackedFloat32Array:
	var n := int(0.3 * float(RATE))
	var out := PackedFloat32Array()
	out.resize(n)
	var rng := RandomNumberGenerator.new()
	rng.seed = 0x5d3
	var lp := 0.0
	for i in n:
		var t := float(i) / float(n)
		lp = lerpf(lp, rng.randf_range(-1.0, 1.0), lerpf(0.05, 0.4, t))
		out[i] = lp * _envelope(t, _attack(0.012, n), 2.2, 0.66) * 0.4
	return out


## A level cleared. Up a fifth and back, four notes. Nothing else is happening, so
## this can take its time in a way the burger cannot.
static func _level_clear() -> PackedFloat32Array:
	return _arp([C5, G5, E5, G5], 0.06, 2.0, 3.0)


## Out of chefs. The level-clear tune inverted and slowed, so the player hears the
## one they just failed to finish rather than a new one.
static func _game_over() -> PackedFloat32Array:
	return _arp([C5, A3, F4, C4], 0.09, 2.0, 4.0)


## Every level cleared. The longest effect in the game, because it is the end of
## the run and this is the one place where waiting is the right thing to do.
static func _win() -> PackedFloat32Array:
	return _arp([C5, E5, G5, B5, G5, B5, D6], 0.08, 2.0, 4.0, 0.25)


# --- Synthesis ---------------------------------------------------------------


## One oscillator: the shape most effects here are built from.
##
## `f0` and `f1` are the pitch at the start and the end in hertz, `amp` how loud,
## `attack` how long to take getting there, `decay` how hard the fade bites, `noise`
## how much noise to mix under it, `duty` the square wave's duty cycle, `hold` the
## fraction of the effect spent at full volume, and `alternate` whether to play two
## notes on the halves of it instead of sliding between `f0` and `f1`.
##
## `duty` is a real duty cycle and 0.5 is a full-width square. The values below sit
## between a quarter and a half because anything much thinner than a quarter is a
## click train rather than a note.
static func _voice(dur: float, f0: float, f1: float, amp: float, attack: float,
		decay: float, noise: float, duty: float, hold: float = 0.0,
		alternate: bool = false) -> PackedFloat32Array:
	var n := maxi(int(dur * float(RATE)), 1)
	var out := PackedFloat32Array()
	out.resize(n)
	var rng := RandomNumberGenerator.new()
	rng.seed = int(f0 * 1000.0) + n
	for i in n:
		var t := float(i) / float(n)
		# Phase advances in *seconds*, not in normalised progress. `t` runs 0 to 1
		# across the whole effect, so using it as a time multiplies every frequency
		# by the effect's length in samples - which is far past Nyquist, and aliases
		# the lot into a click.
		var secs := float(i) / float(RATE)
		var f := f0 if t < 0.5 and alternate else f1 if alternate \
				else lerpf(f0, f1, t)
		var v := _square(_phase(secs, f), duty) \
				+ noise * rng.randf_range(-1.0, 1.0)
		out[i] = v * _envelope(t, _attack(attack, n), decay, hold) * amp
	return out


## One square note whose pitch sweeps up to `hi` and back down to `lo` inside the
## sound - the arcade "wocka" the chef's walk is built from.
##
## It is a *single* note with a warp in it rather than two notes, which is what
## separates a wocka from a beep-beep: two notes each carry their own envelope, so
## the seam between them falls to silence and it reads as two blips. Here one
## envelope spans the whole thing, the pitch is low at both ends and high in the
## middle, and the result is one rounded "wa-ka".
static func _wocka(dur: float, lo: float, hi: float, amp: float,
		duty: float) -> PackedFloat32Array:
	var n := maxi(int(dur * float(RATE)), 1)
	var out := PackedFloat32Array()
	out.resize(n)
	for i in n:
		var t := float(i) / float(n)
		var secs := float(i) / float(RATE)
		# 0 at both ends, 1 in the middle, so the pitch visits `lo` twice and `hi` once.
		var tri := 1.0 - absf(2.0 * t - 1.0)
		var f := lerpf(lo, hi, tri)
		# Held until the falling half has been heard and only then released,
		# unlike the short thuds: a wocka is two syllables one after the other,
		# and an envelope that started fading at the midpoint spent the fall in
		# silence, which heard as a single rising "wock" rather than a "wock-a".
		out[i] = _square(_phase(secs, f), duty) \
				* _envelope(t, _attack(MIN_ATTACK, n), 1.2, 0.78) * amp
	return out


## A run of notes, which is what the jingles are: a list of pitches and nothing
## else, every note the same length and shape.
##
## `tail` multiplies the *last* note so a jingle ends rather than stops, and it is
## a multiplier above one - a value below one truncates the note that carries the
## resolution, and the jingle arrives as a run of notes with nothing on the end.
static func _arp(notes: Array, note_dur: float, decay: float, tail: float,
		shape: float = 0.5) -> PackedFloat32Array:
	var out := PackedFloat32Array()
	for i in notes.size():
		var f: float = notes[i]
		out.append_array(_voice(note_dur * (tail if i == notes.size() - 1 else 1.0),
				f, f, 0.3, 0.0, decay, 0.0, shape))
	return out


## One-pole lowpass over seeded noise, the body of the three effects that are meant
## to be spray, splat and rush rather than notes. `from` and `to` are the filter's
## openness at the start and the end, and which way they run is the difference
## between a hiss that settles and a hiss that rises.
static func _noise(dur: float, from: float, to: float, seed_value: int,
		amp: float, decay: float, hold: float = 0.0,
		attack: float = 0.0) -> PackedFloat32Array:
	var n := maxi(int(dur * float(RATE)), 1)
	var out := PackedFloat32Array()
	out.resize(n)
	var rng := RandomNumberGenerator.new()
	rng.seed = seed_value
	var lp := 0.0
	for i in n:
		var t := float(i) / float(n)
		lp = lerpf(lp, rng.randf_range(-1.0, 1.0), lerpf(from, to, t))
		out[i] = lp * _envelope(t, _attack(attack, n), decay, hold) * amp
	return out


## A recipe's requested attack, in seconds, as the fraction of the effect the
## envelope needs - and `MIN_ATTACK` when the recipe did not ask for one.
static func _attack(attack: float, n: int) -> float:
	var secs := attack if attack > 0.0 else MIN_ATTACK
	return clampf(secs * float(RATE) / float(n), 0.0, 1.0)


## Amplitude over the life of an effect: up over `attack` as a fraction of it, held,
## then away on a curve. Every effect uses this, so they all end the same quiet way.
##
## `hold` is the fraction spent at full volume, so the fade always has the rest of
## the effect to work with and always lands on silence. The fade runs from `hold` to
## the end whether or not `hold` is zero - guarding it behind `hold > 0` leaves a
## note at full volume for its whole length, which is a buzz that starts and ends
## on a click.
static func _envelope(t: float, attack: float, decay: float,
		hold: float = 0.0) -> float:
	var a := 1.0 if attack <= 0.0 else clampf(t / attack, 0.0, 1.0)
	var f := 1.0
	if t > hold:
		f = 1.0 - (t - hold) / maxf(1.0 - hold, 0.001)
	# A bigger `decay` bites sooner, and so is what makes a thud die and a note ring.
	return a * pow(clampf(f, 0.0, 1.0), maxf(decay, 0.001))


## Phase in cycles at a time in seconds, for a frequency. `fposmod` wraps it, so a
## pitch slide does not click at the seam a raw `secs * f` would not have anyway.
static func _phase(secs: float, f: float) -> float:
	return fposmod(secs * f, 1.0)


## A square wave with a duty cycle, which is the whole oscillator vocabulary of
## this file.
static func _square(phase: float, duty: float) -> float:
	return 1.0 if phase < duty else -1.0
